### ISSUE TITLE
Make title changeable

### ISSUE THREAD

**Issue by JanRegent** [GhostWalker562/flutterbook#1]
title: 'Flutterbook' is harcoded.
Can do title changeable?
Thanks a lot for your work :-)

**Comment by GhostWalker562** [comment]
I can definitely do that. I'm currently busy at the moment, but when I'm home I'll implement it as soon as possible.
Thanks 😁

**Comment by GhostWalker562** [comment]
You can now change the title. The parameter is named `header`
