### ISSUE TITLE
Add online demo

### ISSUE THREAD

**Issue by Albert221** [GhostWalker562/flutterbook#16]
Hello! I'm really excited to see such package. I haven't yet had a chance to test it myself, but I'm looking forward to! 

What would be really handy though is to have an online hosted demo of a storybook created using your package

All the best!

**Comment by Albert221** [comment]
...I see it's already here: https://flutterbook.vercel.app/#/stories/library/button/primary

Okay, so it would be convenient to have a link to the demo somewhere on the top of the readme

**Comment by GhostWalker562** [comment]
Loved to hear!
Currently @Josiassejod1 is managing the project. Currently there is a demo on the README but if you have more suggestions, send it to him :)

**Comment by Josiassejod1** [comment]
Hey @Albert221, I just put the demo link at the top !
