### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by Josiassejod1** [GhostWalker562/flutterbook#5]
@aarontwf 
@GhostWalker562 

How can I help contribute to the codebase, what's on the roadmap? Contact me

**Comment by GhostWalker562** [comment]
Cool! I've been away for awhile to work on other projects but I plan on working on this package by the end of November. For now, you can wait or take a look at the roadmap on the README. But I'll comment on this PR again when I'm starting.

**Comment by Josiassejod1** [comment]
Hey thanks for that look forward to helping out on this project.

**Comment by Doetheman** [comment]
Also want to contribute on this. Specifically on implementing the doc feature and device simulator feature

**Comment by GhostWalker562** [comment]
@Doetheman of course that'd be great 😁. To reiterate, I won't be starting up this project until  the end November so I'll make sure to comment on this PR.

**Comment by GhostWalker562** [comment]
Currently working on the docs feature. If you want to contribute, please take a look at the roadmap and make an issue saying that you are fixing that feature
